
set_eval: 1 2 3 4 5 6 6 7 8 9


# 1.ws
# 2.ds
# 3.fft
# 4.dj
# 5.pt
# 6.sha
# 7.bm
# 8.ss
# 9.crc

1:
	./run.sh whetstone TH1
	cp final_output/final_output_binary ./evals/ws/th1
	./run.sh whetstone TH2
	cp final_output/final_output_binary ./evals/ws/th2
	./run.sh whetstone TH3
	cp final_output/final_output_binary ./evals/ws/th3
	./run.sh whetstone TH4
	cp final_output/final_output_binary ./evals/ws/th4


2:
	./run.sh dhrystone TH1
	cp final_output/final_output_binary ./evals/ds/th1
	./run.sh dhrystone TH2
	cp final_output/final_output_binary ./evals/ds/th2
	./run.sh dhrystone TH3
	cp final_output/final_output_binary ./evals/ds/th3
	./run.sh dhrystone TH4
	cp final_output/final_output_binary ./evals/ds/th4


3:
	./run.sh fft TH1
	cp final_output/final_output_binary ./evals/fft/th1
	./run.sh fft TH2
	cp final_output/final_output_binary ./evals/fft/th2
	./run.sh fft TH3
	cp final_output/final_output_binary ./evals/fft/th3
	./run.sh fft TH4
	cp final_output/final_output_binary ./evals/fft/th4



4:
	./run.sh dijkstra TH1
	cp final_output/final_output_binary ./evals/dj/th1
	./run.sh dijkstra TH2
	cp final_output/final_output_binary ./evals/dj/th2
	./run.sh dijkstra TH3
	cp final_output/final_output_binary ./evals/dj/th3
	./run.sh dijkstra TH4
	cp final_output/final_output_binary ./evals/dj/th4



5:
	./run.sh patricia TH1
	cp final_output/final_output_binary ./evals/pt/th1
	./run.sh patricia TH2
	cp final_output/final_output_binary ./evals/pt/th2
	./run.sh patricia TH3
	cp final_output/final_output_binary ./evals/pt/th3
	./run.sh patricia TH4
	cp final_output/final_output_binary ./evals/pt/th4



6:
	./run.sh sha TH1
	cp final_output/final_output_binary ./evals/sha/th1
	./run.sh sha TH2
	cp final_output/final_output_binary ./evals/sha/th2
	./run.sh sha TH3
	cp final_output/final_output_binary ./evals/sha/th3
	./run.sh sha TH4
	cp final_output/final_output_binary ./evals/sha/th4



7:
	./run.sh basicmath TH1
	cp final_output/final_output_binary ./evals/bm/th1
	./run.sh basicmath TH2
	cp final_output/final_output_binary ./evals/bm/th2
	./run.sh basicmath TH3
	cp final_output/final_output_binary ./evals/bm/th3
	./run.sh basicmath TH4
	cp final_output/final_output_binary ./evals/bm/th4

7_clean:
	rm -f ./evals/bm/th1/final_output_binary
	rm -f ./evals/bm/th2/final_output_binary
	rm -f ./evals/bm/th3/final_output_binary
	rm -f ./evals/bm/th4/final_output_binary


8:
	./run.sh stringsearch TH1
	cp final_output/final_output_binary ./evals/ss/th1
	./run.sh stringsearch TH2
	cp final_output/final_output_binary ./evals/ss/th2
	./run.sh stringsearch TH3
	cp final_output/final_output_binary ./evals/ss/th3
	./run.sh stringsearch TH4
	cp final_output/final_output_binary ./evals/ss/th4



9:
	./run.sh crc TH1
	cp final_output/final_output_binary ./evals/crc/th1
	./run.sh crc TH2
	cp final_output/final_output_binary ./evals/crc/th2
	./run.sh crc TH3
	cp final_output/final_output_binary ./evals/crc/th3
	./run.sh crc TH4
	cp final_output/final_output_binary ./evals/crc/th4

